# Generated by Django 4.2.7 on 2023-11-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "registration_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("brand", models.CharField(max_length=25)),
                ("model", models.CharField(max_length=25)),
                ("year_of_release", models.DateField()),
                ("payload", models.IntegerField()),
                ("appointment", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Airfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("runway_class", models.CharField(max_length=2)),
                ("class_by_take_off_weight", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("passport", models.CharField(max_length=30)),
                (
                    "marital_status",
                    models.IntegerField(choices=[(0, "Single"), (1, "Married")]),
                ),
                ("education", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=30)),
                ("e_mail", models.EmailField(max_length=254)),
                ("rank", models.CharField(max_length=25)),
                ("employ_date", models.DateField()),
                ("work_experience", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FuelAndLubricants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_CLM", models.CharField(max_length=25)),
                ("class_CLM", models.IntegerField()),
                ("type_CLM", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinates", models.CharField(max_length=20)),
                ("landscape", models.CharField(max_length=100)),
                ("peculiarity", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "landing_airfield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_airfield",
                        to="mesais.airfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WheatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField()),
                ("precipitation", models.IntegerField()),
                ("wind_speed", models.IntegerField()),
                ("wind_direction", models.CharField(max_length=100)),
                ("humidity", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesais.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_profile", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesais.region"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesais.route"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="route",
            name="region",
            field=models.ManyToManyField(
                through="mesais.RouteComposition", to="mesais.region"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="take_off_airfield",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="take_off_airfield",
                to="mesais.airfield",
            ),
        ),
        migrations.CreateModel(
            name="FuelCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_of_CLM", models.IntegerField()),
                (
                    "name_CLM",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mesais.fuelandlubricants",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=100)),
                ("date_flight", models.DateField()),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesais.crew"
                    ),
                ),
                (
                    "registration_number_aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mesais.aircraft",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesais.route"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenditureCLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expenditure_CLM", models.IntegerField()),
                (
                    "airfield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mesais.airfield",
                    ),
                ),
                (
                    "name_CLM",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mesais.fuelandlubricants",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrewComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesais.crew"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mesais.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crew",
            name="employee",
            field=models.ManyToManyField(
                through="mesais.CrewComposition", to="mesais.employee"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="fixed_crew",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mesais.crew"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="home_airfield",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mesais.airfield"
            ),
        ),
    ]
